package database;

public class Database {
    public static String[][] bd() {
        String[][] data = {
                { "Odie", "Perro", "guau guau" },
                { "Snoopy", "Perro", "guau guau" },
                { "Slinky", "Perro", "guau guau" },
                { "Toto", "Perro", "guau guau" },
                { "Balto", "Perro", "guau guau" },
                { "Marley", "Perro", "guau guau" },
                { "Bolt", "Perro", "guau guau" },
                { "Golfo", "Perro", "guau guau" },
                { "Pongo", "Perro", "guau guau" },
                { "Beethoven", "Perro", "guau guau" },
                { "Luna", "Gato", "miau miau" },
                { "Hachiko", "Perro", "guau guau" },
                { "Lola", "Gato", "miau miau" },
                { "Benji", "Perro", "guau guau" },
                { "Mia", "Gato", "miau miau" },
                { "Scooby", "Perro", "guau guau" },
                { "Olivia", "Gato", "miau miau" },
                { "Clifford", "Perro", "guau guau" },
                { "Misha", "Gato", "miau miau" },
                { "Astro", "Perro", "guau guau" },
                { "Frida", "Gato", "miau miau" },
                { "Goofy", "Perro", "guau guau" },
                { "Lucy", "Gato", "miau miau" },
                { "Chip", "Perro", "guau guau" },
                { "Nala", "Gato", "miau miau" },
                { "Einstein", "Perro", "guau guau" },
                { "Nina", "Gato", "miau miau" },
                { "Fang", "Perro", "guau guau" },
                { "Simba", "Gato", "miau miau" },
                { "Frank", "Perro", "guau guau" },
                { "Simón", "Gato", "miau miau" },
                { "Rin Tin Tin", "Perro", "guau guau" },
                { "Oliver", "Gato", "miau miau" },
                { "Milo", "Perro", "guau guau" },
                { "Milo", "Gato", "miau miau" },
                { "Truman", "Perro", "guau guau" },
                { "Teo", "Gato", "miau miau" },
                { "Uggie", "Perro", "guau guau" },
                { "Tom", "Gato", "miau miau" },
                { "Bingo", "Perro", "guau guau" },
                { "Teo", "Gato", "miau miau" },
                { "Blue", "Perro", "guau guau" },
                { "Pancho", "Gato", "miau miau" },
                { "Cometa", "Perro", "guau guau" },
                { "Felipe", "Gato", "miau miau" },
                { "Krypto", "Perro", "guau guau" },
                { "Gato", "miau miau", "Gato", "miau miau" },
                { "Max", "Perro", "guau guau" },
                { "Salem", "Gato", "miau miau" },
                { "Huesos", "Perro", "guau guau" },
        };
        return data;
    }
}
